version: "3.7"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=Admin33Admin77
    networks:
      - typebot_rede
    #ports:
    #  - 5432:5432
    volumes:
      - postgres_typebot:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  postgres_typebot:
    external: false
    name: postgres_typebot

networks:
  typebot_rede:
    external: false
    name: typebot_rede